# Site settings
title: Crux Design Studio
email: team@crux.ph
description: >
  More than just a creative team, Crux commits itself to helping people, brands, and companies solve problems through design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crux.ph" # the base hostname & protocol for your site
twitter_username: cruxph
github_username:  cruxph
permalink: pretty

# Build settings
markdown: kramdown

#Collections
collections:
    carousel_contents:
        output: true
    works:
        output: true
        permalink: /works/:name/

sass:
  style: :compressed
