# Site settings
title: Crux Design Studio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crux.ph" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty

# Build settings
markdown: kramdown

#Collections
collections:
    banner_contents:
        output: true
    works:
        output: true
        permalink: /works/:name/

sass:
  style: :compressed
